defaults:
  - dataset: ABIDE
  - model: lhdformer
  - optimizer: adam
  - training: training
  - datasz: 100p
  - preprocess: mixup

repeat_time: 10
log_path: result
save_learnable_graph: False
save_attn_weights: False
save_test_attn_weights: False

# wandb
wandb_entity: eggroup
project: brainnetworktransformer
